spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:com/chushiy/study/mpj/mapper/*Mapper.xml
  type-aliases-package: com.chushiy.study.mpj.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.chushiy.study.mpj: debug
